services:
  mongodb:
    image: mongo:6
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASS}
    volumes:
      - mongo_data:/data/db
    networks:
      - monitor-net
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')", "-u", "${MONGO_USER}", "-p", "${MONGO_PASS}", "--authenticationDatabase", "admin"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  users:
    build: ./users
    container_name: users
    image: ghcr.io/arquisoft/yovi_en3a-users:latest
    environment:
      - MONGODB_URI=mongodb://${MONGO_USER}:${MONGO_PASS}@mongodb:27017/usersdb?authSource=admin
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - monitor-net

  game-manager:
    build: ./gamemanager
    container_name: gamemanager
    image: ghcr.io/arquisoft/yovi_en3a-game-manager:latest
    environment:
      - MONGODB_URI=mongodb://${MONGO_USER}:${MONGO_PASS}@mongodb:27017/gamesdb?authSource=admin
      - GAMEY_SERVICE_URL=http://gamey:4000
      - USERS_SERVICE_URL=http://users:3000
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - monitor-net

  gamey:
    build: ./gamey
    container_name: gamey
    image: ghcr.io/arquisoft/yovi_en3a-gamey:latest
    networks:
      - monitor-net

  gatewayservice:
    build: ./gatewayservice
    container_name: gatewayservice
    image: ghcr.io/arquisoft/yovi_en3a-gatewayservice:latest
    ports:
      - "8000:8000"
    environment:
      - USERS_SERVICE_URL=http://users:3000
      - GAME_MANAGER_URL=http://game-manager:5000
      - GAMEY_SERVICE_URL=http://gamey:4000
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - users
      - gamey
      - game-manager
    networks:
      - monitor-net

  webapp:
    build:
      context: ./webapp
      args:
        - VITE_API_URL=http://localhost:8000
    container_name: webapp
    image: ghcr.io/arquisoft/yovi_en3a-webapp:latest
    ports:
      - "8080:80"
    depends_on:
      - gatewayservice
    networks:
      - monitor-net

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./users/monitoring/prometheus:/etc/prometheus
    networks:
      - monitor-net

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "9091:3000"
    volumes:
      - ./users/monitoring/grafana/provisioning:/etc/grafana/provisioning
    networks:
      - monitor-net

networks:
  monitor-net:
    driver: bridge

volumes:
  mongo_data:
