sonar.organization=arquisoft
sonar.host.url=https://sonarcloud.io
sonar.projectKey=Arquisoft_yovi_en3a
sonar.projectName=yovi_en3a

sonar.sources=webapp/src,users,gamey/src,gatewayservice,gamemanager
sonar.tests=webapp/src,users/__tests__,gamey/src,gatewayservice/__tests__,gamemanager/__tests__
sonar.test.inclusions=**/*.test.tsx,**/*.test.js
sonar.javascript.lcov.reportPaths=webapp/coverage/lcov.info,users/coverage/lcov.info,gatewayservice/coverage/lcov.info,gamemanager/coverage/lcov.info
sonar.rust.lcov.reportPaths=gamey/lcov.info