ifndef::imagesdir[:imagesdir: ../images]

[[section-context-and-scope]]
== Context and Scope

ifdef::arc42help[]
[role="arc42help"]
****
.Contents
Context and scope - as the name suggests - delimits your system (i.e. your scope) from all its communication partners
(neighboring systems and users, i.e. the context of your system). It thereby specifies the external interfaces.

If necessary, differentiate the business context (domain specific inputs and outputs) from the technical context (channels, protocols, hardware).

.Motivation
The domain interfaces and technical interfaces to communication partners are among your system's most critical aspects. Make sure that you completely understand them.

.Form
Various options:

* Context diagrams
* Lists of communication partners and their interfaces.


.Further Information

See https://docs.arc42.org/section-3/[Context and Scope] in the arc42 documentation.

****
endif::arc42help[]

=== Business Context

[plantuml, "Business context",png]
----
skinparam linetype ortho

actor User
actor "External Bots" as Bots

rectangle YOVI as YOVI

User -[hidden]-> YOVI
YOVI -[hidden]-> Bots

User ---> YOVI : Login credentials \n Game decisions
YOVI ---> User : Game state \n Statistics/History 

Bots <---> YOVI : API requests \n Game data \n Movements
----

.YOVI
[options="header"]
|===
| Communication Partner | Input | Output

| User
| - Login credentials +
  - Game decisions + 
  - Data requests
| - Authentication result +
  - Game state +
  - Statistics / History

| External Bots
| - API requests
| - Game data +
  - Game actions
|===

ifdef::arc42help[]
[role="arc42help"]
****
.Contents
Specification of *all* communication partners (users, IT-systems, ...) with explanations of domain specific inputs and outputs or interfaces.
Optionally you can add domain specific formats or communication protocols.

.Motivation
All stakeholders should understand which data are exchanged with the environment of the system.

.Form
All kinds of diagrams that show the system as a black box and specify the domain interfaces to communication partners.

Alternatively (or additionally) you can use a table.
The title of the table is the name of your system, the three columns contain the name of the communication partner, the inputs, and the outputs.

****
endif::arc42help[]

=== Technical Context

[plantuml, "Technical context",png]
----
actor User
actor ExternalBots as Bots

node "YOVI" {

    rectangle "Web Frontend" as Frontend
    
    rectangle "Gateway Service" as API

    rectangle "Users Service" as Service

    rectangle "GameY" as Game {
        rectangle "Bot"
    }

    rectangle "Game Manager" as Manager

    database "MongoDB" as DB
}

User --> Frontend : HTTPS
Bots --> API : HTTPS

Frontend --> API : HTTPS

API --> Service
API --> Manager
API --> Game

Service <--> DB : MongoDB
Manager <--> DB : MongoDB
----

|===
| Communication Partner | Input | Output

| User
| - Login credentials +
  - Game moves / Strategy selection
  - Data requests
| - Authentication result +
  - Game state +
  - Statistics / History

| Web Frontend
| - Requests from the user (login, moves, strategy)
| - Forwards requests to Gateway Service

| Gateway Service
| - Requests from Frontend +
  - Requests from External Bots
| - Forwards requests to Users Service, Game Manager, GameY +
  - Responds back to Frontend and Bots

| Users Service
| - Registration/Login data from API +
  - Requests from API (stats, history)
| - User created / validated +
  - Authentication result +
  - Data from MongoDB

| GameY
| - Game moves from API +
  - Bot decisions (internal)
| - Game state updates +
  - Bot actions +
  - Responses to the API

| Bot (internal)
| - Game state
| - Next action

| MongoDB
| - Queries from Users Service +
  - Queries from Game Manager
| - Returns requested user and game data
|===


ifdef::arc42help[]
[role="arc42help"]
****
.Contents
Technical interfaces (channels and transmission media) linking your system to its environment. In addition a mapping of domain specific input/output to the channels, i.e. an explanation which I/O uses which channel.

.Motivation
Many stakeholders make architectural decision based on the technical interfaces between the system and its context. Especially infrastructure or hardware designers decide these technical interfaces.

.Form
E.g. UML deployment diagram describing channels to neighboring systems,
together with a mapping table showing the relationships between channels and input/output.

****
endif::arc42help[]