ifndef::imagesdir[:imagesdir: ../images]

[[section-runtime-view]]
== Runtime View
This section illustrates key runtime operations and interactions among the system’s components.

ifdef::arc42help[]
[role="arc42help"]
****
.Contents
The runtime view describes concrete behavior and interactions of the system’s building blocks in form of scenarios from the following areas:

* important use cases or features: how do building blocks execute them?
* interactions at critical external interfaces: how do building blocks cooperate with users and neighboring systems?
* operation and administration: launch, start-up, stop
* error and exception scenarios

Remark: The main criterion for the choice of possible scenarios (sequences, workflows) is their *architectural relevance*. It is *not* important to describe a large number of scenarios. You should rather document a representative selection.

.Motivation
You should understand how (instances of) building blocks of your system perform their job and communicate at runtime.
You will mainly capture scenarios in your documentation to communicate your architecture to stakeholders that are less willing or able to read and understand the static models (building block view, deployment view).

.Form
There are many notations for describing scenarios, e.g.

* numbered list of steps (in natural language)
* activity diagrams or flow charts
* sequence diagrams
* BPMN or EPCs (event process chains)
* state machines
* ...


.Further Information

See https://docs.arc42.org/section-6/[Runtime View] in the arc42 documentation.

****
endif::arc42help[]

=== User registration

This scenario shows how a user registers in the system, including how the frontend and backend communicate.

[plantuml,"Sequence diagram - Login ",png]
----
hide footbox

actor User
participant "Webapp" as Webapp
participant "Gateway Service" as Gateway
participant "Users Service" as Service

User -> Webapp : Fill form
Webapp -> Gateway : Forward request
Gateway -> Service : POST /createuser\n{ username, password, email ... }
Service --> Service : { Validate input }

alt Success
    Service --> Webapp : { message }
    Gateway --> Webapp : Forward response
    Webapp -> User : Show welcome message
else Error
    Service --> Webapp : { error }
    Gateway --> Webapp : Forward response
    Webapp -> User : Show error message
end
----

=== User Login

This scenario shows how a user logs into the system, including how the frontend and backend communicate.

[plantuml,"Sequence diagram - Login ",png]
----
hide footbox

actor User
participant "Webapp" as Webapp
participant "Gateway Service" as Gateway
participant "Users Service" as Service

User -> Webapp : Fill form
Webapp -> Gateway : Forward request
Gateway -> Service : POST /login\n{ username, password }

alt Success
    Service --> Webapp : { message }
    Gateway --> Webapp : Forward response
    Webapp -> User : Show welcome message and redirect to main menu
else Error
    Service --> Webapp : { error }
    Gateway --> Webapp : Forward response
    Webapp -> User : Show error message
end
----



=== Game loop

This scenario shows how a user plays a game, including interactions with the web app, game core, and bot service.

[plantuml,"Sequence diagram - Game Loop ",png]
----

actor "Player" as User
participant "WebApp" as Web
participant "Game Core" as GameCore

participant "Bot Service" as Bot

User -> Web : Start Game


Web --> User : Game started


loop until game over
  
    User -> Web : make move
    Web -> GameCore : process player move
    GameCore -> GameCore : updated state

    GameCore -> GameCore : check if game over
        GameCore --> Web : update state
        Web --> User : show state
    

   
    GameCore -> Bot : send current board state
    Bot --> GameCore : bot's next move
    GameCore -> GameCore : update state

    GameCore -> GameCore : check if game over
    

    GameCore --> Web : updated state
    deactivate GameCore

    Web --> User : show state
end

 
Web --> User : Game Over

----
